version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    environment:
      POSTGRES_USER: hato
      POSTGRES_PASSWORD: hato72
      POSTGRES_DB: hato
    networks:
      - lesson
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: hato
      POSTGRES_PASSWORD: hato72
      POSTGRES_DB: hato
    networks:
      - lesson

networks:
  lesson:
